spring:
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 60000
        validation-timeout: 3000
        idle-timeout: 60000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 10
        is-read-only: false
        connection-test-query: select 1
        pool-name: velHikariCP

      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          url: jdbc:mysql://127.0.0.1:3306/vel?autoReconnect=true&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=GMT%2b8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 300

# 上传配置
upload:
  # 本地
  local:
    # 匹配路径
    path-pattens: file
    # windows
    file-path: F:/opt/nginx/file/
    # linux
    #    file-path: /opt/nginx/image/
    # 图片访问地址
    localhost: http://127.0.0.1:${server.port}/${upload.local.path-pattens}
  #阿里oss
  ali:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTA*********RYd
    access-key-secret: NwJl***********ewtIi8
    bucket-name: lets-sys-back
    file-path: test/file/
    public-bucket-name: https://******.oss-cn-guangzhou.aliyuncs.com